FROM node AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nodesource/nsolid

RUN npm install pm2 -g

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/ecosystem.config.js ./dist

COPY package*.json ./

RUN npm install

RUN mkdir -p /root/.pm2

ENV NODE_ENV=production

ENV PORT=3005

CMD ["pm2-runtime", "start", "dist/ecosystem.config.js", "--env", "production"]